site_name: STB 使用教程
pages:
- 环境搭建: buildenv.md
- 介绍: index.md
- 开始使用: getting-started.md
- 教程: tutorial.md
- 高级技巧: advenced.md
- 推荐模块: recommend.md
- 手机应用打包帮助: cordova.md
- 前端应用发布: deploy.md
- 启动端口修改: updateport.md
- 版本历史: release.md
- 更多: moreinfo.md
- 联系我们: contact.md
theme: readthedocs